import { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Localization from 'expo-localization';

export type LanguageCode = 'en' | 'ko' | 'ja' | 'zh' | 'vi';

export const translations: Record<
  LanguageCode,
  Record<string, string | Record<string, string>>
> = {
  en: {
    email: 'Email',
    password: 'Password',
    signup: 'Sign Up',
    forgot: 'Forgot Password?',
    or: 'Or login with',
    selectLanguage: 'Select Language',
    noticeTitle: 'Notice',
    notice1: 'Speak loudly near the microphone.',
    notice2: 'AI response may be delayed in case of traffic surge.',
    notice3: 'You need to repurchase after one year.',
    notice4: 'Free talk mode may change later.',
    wrongPassword: 'Incorrect password.',
    emailNotFound: 'Email is not registered.',
    emptyFields: 'Please enter both email and password.',
    alertTitle: 'Notice',
    trialExpiredMessage: 'Your 3-day trial has ended.\nPlease purchase to continue.',
    trialExpiredTitle: '⏰ Trial Expired',
    purchaseNow: 'Purchase Now',
    cancelPurchase: 'Cancel',
    appName: 'SamSpeak',
    enterId: 'User ID must contain only letters and numbers',
    login: 'Login',
    returnToLanguageSelection: 'Return to language selection',
    error: 'Error',
    loginFailed: 'Login Failed',
    tryAgain: 'Please try again.',
    rememberId: 'Remember ID',
    invalidUserIdTitle: 'Invalid User ID',
    dashboard: {
      loading: "Loading...",
      myAccount: "My Account",
      id: "ID",
      name: "Name",
      admin: "Admin",
      premium: "Premium",
      trial: "Trial",
      freeUser: "Free User",
      voice: "☞ Voice settings can only be changed in the device settings.",
      male: "Male",
      female: "Female",
      subscription: "Subscription",
      status: "Status",
      expiresAt: "Expires At",
      remainingDays: "Remaining {days} days",
      remainingTrialDays: "Trial {days} days left",
      subscribe: "Subscribe",
      extendSubscription: "Extend",
      cancelSubscription: "Cancel Subscription",
      refresh: "Refresh",
      studyProgress: "Study Progress",
      totalMinutes: " -. Total Study Time",
      todayMinutes: " -. Today's Study Time",
      todayTopics: "Today's Topics",
      noStudyToday: "No study today",
      lastStudy: " -. Last Study",
      noStudyHistory: "No history available",
      rank: "Study Ranking",
      overallRank: "Overall",
      beginnerRank: "Beginner",
      intermediateRank: "Intermediate",
      advancedRank: "Advanced",
      dailyChart: "Daily Study",
      weeklyChart: "Weekly Study",
      monthlyChart: "Monthly Study",
      support: "Support",
      emailSupport: "For inquiries, please contact us at bruste68@gmail.com.",
      faq: "FAQ",
      settings: "Settings",
      appVersion: "App Version",
      logout: "Logout",
      withdraw: "Withdraw",
      noData: "No data",
      business: "Business",
      meeting: "Meeting",
      presentation: "Presentation",
      daily: "Daily",
      shopping: "Shopping",
      restaurant: "Restaurant",
      travel: "Travel",
      maleStandard: "Male (Standard)",
      maleChild: "Male (Child)",
      femaleStandard: "Female (Standard)",
      femaleChild: "Female (Child)",
    },
    overlay: {
      myInfo: "My Info",
      viewAll: "View All",
      close: "Close",
    },
    resumeDialog: {
      title: "Continue Practice?",
      desc: "You were practicing before the app was paused. Would you like to continue?",
      continue: "Continue",
      restart: "Restart",
      exit: "Exit",
    },
  },
  ko: {
    email: '이메일',
    password: '비밀번호',
    signup: '회원가입',
    forgot: '비밀번호 찾기',
    or: '또는 SNS로 로그인',
    selectLanguage: '언어 선택',
    noticeTitle: '공지사항',
    notice1: '마이크 근처에서 크게 말해주세요.',
    notice2: '사용자가 많을 경우 AI 응답이 지연될 수 있습니다.',
    notice3: '1년 후 재구매가 필요합니다.',
    notice4: '자유 대화 모드는 추후 결정될 수 있습니다.',
    wrongPassword: '비밀번호가 올바르지 않습니다.',
    emailNotFound: '가입되지 않은 이메일입니다.',
    emptyFields: '이메일과 비밀번호를 모두 입력해주세요.',
    alertTitle: '알림',
    trialExpiredMessage: '3일 체험판이 만료되었습니다.\n정식 버전을 구매해주세요.',
    trialExpiredTitle: '⏰ 체험 종료',
    purchaseNow: '지금 구매하기',
    cancelPurchase: '구매취소',
    appName: 'SamSpeak',
    enterId: '아이디는 영문과 숫자만 입력 가능합니다',
    login: '로그인',
    returnToLanguageSelection: '언어 선택 화면으로 돌아가기',
    error: '오류',
    loginFailed: '로그인 실패',
    tryAgain: '다시 시도해주세요.',
    rememberId: '아이디 기억하기',
    invalidUserIdTitle: '아이디 입력 오류',
    dashboard: {
      loading: "불러오는 중...",
      myAccount: "내 계정",
      id: "아이디",
      name: "이름",
      admin: "관리자",
      premium: "프리미엄",
      trial: "체험 중",
      freeUser: "무료 사용자",
      voice: "☞ 음성설정은 기기 설정에서만 가능합니다.",
      male: "남성",
      female: "여성",
      subscription: "구독 / 결제",
      status: "상태",
      expiresAt: "만료일",
      remainingDays: "잔여 {days}일",
      remainingTrialDays: "체험 {days}일 남음",
      subscribe: "구독하기",
      extendSubscription: "구독연장",
      cancelSubscription: "구독 취소",
      refresh: "새로고침",
      studyProgress: "학습진도",
      totalMinutes: " -. 총누적학습시간",
      todayMinutes: " -. 오늘학습시간",
      todayTopics: "오늘 학습 토픽",
      noStudyToday: "오늘 학습 없음",
      lastStudy: " -. 지난학습",
      noStudyHistory: "학습 이력이 없습니다",
      rank: "학습시간 순위",
      overallRank: "전체 학습자",
      beginnerRank: "초급",
      intermediateRank: "중급",
      advancedRank: "고급",
      dailyChart: "일간 학습 현황",
      weeklyChart: "주간 학습 현황",
      monthlyChart: "월간 학습 현황",
      support: "고객센터",
      emailSupport: "문의사항은 bruste68@gmail.com 으로 보내주세요.",
      faq: "FAQ",
      settings: "설정 / 기타",
      appVersion: "앱 버전",
      logout: "로그아웃",
      withdraw: "회원 탈퇴",
      noData: "데이터 없음",
      business: "비즈니스",
      meeting: "미팅",
      presentation: "발표",
      daily: "일상",
      shopping: "쇼핑",
      restaurant: "식당",
      travel: "여행",
      maleStandard: "남성 (표준)",
      maleChild: "남성 (아동)",
      femaleStandard: "여성 (표준)",
      femaleChild: "여성 (아동)",
    },
    overlay: {
      myInfo: "내 정보",
      viewAll: "전체보기",
      close: "닫기",
    },
    resumeDialog: {
      title: "연습을 계속하시겠습니까?",
      desc: "앱이 일시 중지되기 전에 연습 중이었습니다. 계속하시겠습니까?",
      continue: "계속하기",
      restart: "처음부터",
      exit: "종료",
    },
  },
  ja: {
    email: 'メールアドレス',
    password: 'パスワード',
    signup: '新規登録',
    forgot: 'パスワードを忘れた場合',
    or: 'またはSNSでログイン',
    selectLanguage: '言語を選択',
    noticeTitle: 'お知らせ',
    notice1: 'マイクの近くで大きな声で話してください。',
    notice2: '利用者が多いと応答が遅れることがあります。',
    notice3: '1年後に再購入が必要です。',
    notice4: 'フリートークモードは今後変更される可能性があります。',
    wrongPassword: 'パスワードが正しくありません。',
    emailNotFound: '登録されていないメールアドレスです。',
    emptyFields: 'メールアドレスとパスワードを入力してください。',
    alertTitle: 'お知らせ',
    trialExpiredMessage: '3日間の体験版が終了しました。\n正規版をご購入ください。',
    trialExpiredTitle: '⏰ 体験終了',
    purchaseNow: '今すぐ購入',
    cancelPurchase: '購入をキャンセル',
    appName: 'SamSpeak',
    enterId: 'ユーザーIDは英数字のみ入力できます',
    login: 'ログイン',
    returnToLanguageSelection: '言語選択に戻る',
    error: 'エラー',
    loginFailed: 'ログイン失敗',
    tryAgain: 'もう一度お試しください。',
    rememberId: 'ID記憶',
    invalidUserIdTitle: 'ユーザーID入力エラー',
    dashboard: {
      loading: "読み込み中...",
      myAccount: "マイアカウント",
      id: "ID",
      name: "名前",
      admin: "管理者",
      premium: "プレミアム",
      trial: "体験中",
      freeUser: "無料ユーザー",
      voice: "☞ 音声設定は端末の設定でのみ変更できます。",
      male: "男性",
      female: "女性",
      subscription: "購読 / 決済",
      status: "状態",
      expiresAt: "有効期限",
      remainingDays: "残り {days}日",
      remainingTrialDays: "体験 {days}日 残り",
      subscribe: "購読する",
      extendSubscription: "延長する",
      cancelSubscription: "購読をキャンセル",
      refresh: "更新",
      studyProgress: "学習進捗",
      totalMinutes: " -. 累計学習時間",
      todayMinutes: " -. 今日の学習時間",
      todayTopics: "今日のトピック",
      noStudyToday: "今日は学習していません",
      lastStudy: " -. 前回の学習",
      noStudyHistory: "履歴がありません",
      rank: "学習ランキング",
      overallRank: "全体",
      beginnerRank: "初級",
      intermediateRank: "中級",
      advancedRank: "上級",
      dailyChart: "日別学習",
      weeklyChart: "週別学習",
      monthlyChart: "月別学習",
      support: "サポート",
      emailSupport: "ご不明な点は bruste68@gmail.com までご連絡ください。",
      faq: "FAQ",
      settings: "設定 / その他",
      appVersion: "アプリバージョン",
      logout: "ログアウト",
      withdraw: "退会",
      noData: "データなし",
      business: "ビジネス",
      meeting: "会議",
      presentation: "プレゼン",
      daily: "日常",
      shopping: "ショッピング",
      restaurant: "レストラン",
      travel: "旅行",
      maleStandard: "男性（標準）",
      maleChild: "男性（子供）",
      femaleStandard: "女性（標準）",
      femaleChild: "女性（子供）",
    },
    overlay: {
      myInfo: "マイ情報",
      viewAll: "すべて表示",
      close: "閉じる",
    },
    resumeDialog: {
      title: "練習を続けますか？",
      desc: "アプリが一時停止される前に練習していました。続行しますか？",
      continue: "続ける",
      restart: "最初から",
      exit: "終了",
    },
  },
  zh: {
    email: '电子邮箱',
    password: '密码',
    signup: '注册',
    forgot: '忘记密码？',
    or: '或使用社交账号登录',
    selectLanguage: '选择语言',
    noticeTitle: '公告',
    notice1: '请在麦克风附近大声说话。',
    notice2: '用户量大时，AI 可能响应缓慢。',
    notice3: '一年后需要重新购买。',
    notice4: '自由对话模式可能会有变动。',
    wrongPassword: '密码不正确。',
    emailNotFound: '该邮箱尚未注册。',
    emptyFields: '请输入邮箱和密码。',
    alertTitle: '提示',
    trialExpiredMessage: '3天试用期已结束。\n请购买正式版以继续使用。',
    trialExpiredTitle: '⏰ 试用已结束',
    purchaseNow: '立即购买',
    cancelPurchase: '取消购买',
    appName: 'SamSpeak',
    enterId: '用户ID只能包含字母和数字',
    login: '登录',
    returnToLanguageSelection: '返回语言选择',
    error: '错误',
    loginFailed: '登录失败',
    tryAgain: '请再试一次。',
    rememberId: '记住用户名',
    invalidUserIdTitle: '用户ID输入错误',
    dashboard: {
      loading: "加载中...",
      myAccount: "我的账户",
      id: "账号",
      name: "姓名",
      admin: "管理员",
      premium: "高级",
      trial: "试用中",
      freeUser: "免费用户",
      voice: "☞ 语音设置只能在设备设置中更改。",
      male: "男性",
      female: "女性",
      subscription: "订阅 / 支付",
      status: "状态",
      expiresAt: "到期日",
      remainingDays: "剩余 {days} 天",
      remainingTrialDays: "试用剩余 {days} 天",
      subscribe: "订阅",
      extendSubscription: "续订",
      cancelSubscription: "取消订阅",
      refresh: "刷新",
      studyProgress: "学习进度",
      totalMinutes: " -. 总学习时间",
      todayMinutes: "今日学习时间",
      todayTopics: " -. 今日学习主题",
      noStudyToday: "今天没有学习",
      lastStudy: " -. 上次学习",
      noStudyHistory: "暂无学习记录",
      rank: "学习排名",
      overallRank: "总体",
      beginnerRank: "初级",
      intermediateRank: "中级",
      advancedRank: "高级",
      dailyChart: "每日学习",
      weeklyChart: "每周学习",
      monthlyChart: "每月学习",
      support: "客户服务",
      emailSupport: "如有疑问，请发送邮件至 bruste68@gmail.com。",
      faq: "常见问题",
      settings: "设置 / 其他",
      appVersion: "应用版本",
      logout: "退出登录",
      withdraw: "注销账户",
      noData: "暂无数据",
      business: "商务",
      meeting: "会议",
      presentation: "演讲",
      daily: "日常",
      shopping: "购物",
      restaurant: "餐馆",
      travel: "旅行",
      maleStandard: "男性（标准）",
      maleChild: "男性（儿童）",
      femaleStandard: "女性（标准）",
      femaleChild: "女性（儿童）",
    },
    overlay: {
      myInfo: "我的信息",
      viewAll: "查看全部",
      close: "关闭",
    },
    resumeDialog: {
      title: "继续练习？",
      desc: "应用暂停前您正在练习。是否继续？",
      continue: "继续",
      restart: "重新开始",
      exit: "退出",
    },
  },
  vi: {
    email: 'Email',
    password: 'Mật khẩu',
    signup: 'Đăng ký',
    forgot: 'Quên mật khẩu?',
    or: 'Hoặc đăng nhập bằng',
    selectLanguage: 'Chọn ngôn ngữ',
    noticeTitle: 'Lưu ý',
    notice1: 'Hãy nói to gần micro.',
    notice2: 'Phản hồi AI có thể chậm nếu lượng truy cập cao.',
    notice3: 'Cần mua lại sau 1 năm.',
    notice4: 'Chế độ nói tự do có thể thay đổi trong tương lai.',
    wrongPassword: 'Mật khẩu không đúng.',
    emailNotFound: 'Email chưa được đăng ký.',
    emptyFields: 'Vui lòng nhập email và mật khẩu.',
    alertTitle: 'Thông báo',
    trialExpiredMessage: 'Thời gian dùng thử 3 ngày đã kết thúc.\nVui lòng mua để tiếp tục sử dụng.',
    trialExpiredTitle: '⏰ Đã hết thời gian dùng thử',
    purchaseNow: 'Mua ngay',
    cancelPurchase: 'Hủy',
    appName: 'SamSpeak',
    enterId: 'ID chỉ được phép chứa chữ cái và số',
    login: 'Đăng nhập',
    returnToLanguageSelection: 'Quay lại chọn ngôn ngữ',
    error: 'Lỗi',
    loginFailed: 'Đăng nhập thất bại',
    tryAgain: 'Vui lòng thử lại.',
    rememberId: 'Ghi nhớ ID',
    invalidUserIdTitle: 'Lỗi nhập ID',
    dashboard: {
      loading: "Đang tải...",
      myAccount: "Tài khoản",
      id: "ID",
      name: "Tên",
      admin: "Quản trị viên",
      premium: "Cao cấp",
      trial: "Dùng thử",
      freeUser: "Người dùng miễn phí",
      voice: "☞ Cài đặt giọng nói chỉ có thể thay đổi trong cài đặt thiết bị.",
      male: "Nam",
      female: "Nữ",
      subscription: "Đăng ký / Thanh toán",
      status: "Trạng thái",
      expiresAt: "Ngày hết hạn",
      remainingDays: "Còn {days} ngày",
      remainingTrialDays: "Dùng thử còn {days} ngày",
      subscribe: "Đăng ký",
      extendSubscription: "Gia hạn",
      cancelSubscription: "Hủy đăng ký",
      refresh: "Làm mới",
      studyProgress: "Tiến độ học tập",
      totalMinutes: " -. Tổng thời gian học",
      todayMinutes: " -. Thời gian học hôm nay",
      todayTopics: "Chủ đề hôm nay",
      noStudyToday: "Hôm nay chưa học",
      lastStudy: " -. Buổi học trước",
      noStudyHistory: "Không có lịch sử học",
      rank: "Xếp hạng học tập",
      overallRank: "Tổng thể",
      beginnerRank: "Sơ cấp",
      intermediateRank: "Trung cấp",
      advancedRank: "Cao cấp",
      dailyChart: "Học theo ngày",
      weeklyChart: "Học theo tuần",
      monthlyChart: "Học theo tháng",
      support: "Hỗ trợ",
      emailSupport: "Mọi thắc mắc vui lòng gửi đến bruste68@gmail.com.",
      faq: "FAQ",
      settings: "Cài đặt / Khác",
      appVersion: "Phiên bản ứng dụng",
      logout: "Đăng xuất",
      withdraw: "Rút lui",
      noData: "Không có dữ liệu",
      business: "Kinh doanh",
      meeting: "Cuộc họp",
      presentation: "Thuyết trình",
      daily: "Hằng ngày",
      shopping: "Mua sắm",
      restaurant: "Nhà hàng",
      travel: "Du lịch",
      maleStandard: "Nam (Chuẩn)",
      maleChild: "Nam (Trẻ em)",
      femaleStandard: "Nữ (Chuẩn)",
      femaleChild: "Nữ (Trẻ em)",
    },
    overlay: {
      myInfo: "Thông tin",
      viewAll: "Xem tất cả",
      close: "Đóng",
    },
    resumeDialog: {
      title: "Tiếp tục luyện tập?",
      desc: "Bạn đang luyện tập trước khi ứng dụng bị tạm dừng. Bạn có muốn tiếp tục không?",
      continue: "Tiếp tục",
      restart: "Bắt đầu lại",
      exit: "Thoát",
    },
  },
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<LanguageCode>('en');
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const stored = await AsyncStorage.getItem('appLanguage');
        if (stored && ['en', 'ko', 'ja', 'zh', 'vi'].includes(stored)) {
          setLanguage(stored as LanguageCode);
        } else {
          // ✅ 안전한 locale 처리
          let deviceLang: string = 'en';
          try {
            const locales = Localization.getLocales?.();
            if (Array.isArray(locales) && locales.length > 0) {
              // ✅ null 방지: 기본값 'en'
              deviceLang = locales[0].languageCode ?? 'en';
            }
          } catch (e) {
            console.warn('Localization not available:', e);
          }

          // ✅ zh-Hans, zh-Hant → zh 로 통합
          const defaultLang: LanguageCode =
            ['ko', 'ja', 'vi'].includes(deviceLang)
              ? (deviceLang as LanguageCode)
              : deviceLang.startsWith('zh')
              ? 'zh'
              : 'en';

          setLanguage(defaultLang);
         // await AsyncStorage.setItem('appLanguage', defaultLang);
        }
      } catch (error) {
        console.error('Failed to load language', error);
      } finally {
        setIsReady(true);
      }
    };

    loadLanguage();
  }, []);

  const setAppLanguage = async (lang: LanguageCode) => {
    try {
      await AsyncStorage.setItem('appLanguage', lang);
      setLanguage(lang);
    } catch (error) {
      console.error('Failed to save language', error);
    }
  };

  // ✅ fallback 보강
  const t = translations[language] || translations.en;

  return { language, setLanguage: setAppLanguage, isReady, t };
};